
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t . --verbose
      - echo "Files after installing dependencies:"
      - ls -la
  build:
    commands:
      - echo "Building application..."
artifacts:
  files:
    - '**/*'
