version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
  commands:
    - echo Installing dependencies...
    - pip install -r requirements.txt -t .
    - echo "Files after install:"
    - ls -la
  build:
    commands:
      - echo Building application...
artifacts:
  files:
    - '**/*'
